# -*- coding: utf-8 -*-
"""notebookb3055271d1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/mahikhan5360/notebookb3055271d1.7c08a3f0-a6c6-4ffb-b8d7-a3a4a2f404eb.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20250403/auto/storage/goog4_request%26X-Goog-Date%3D20250403T191436Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D9dc208a60c8d3986f797ad6b5098f95c2ecbee3ef7d4109950e983e04203f910a1e0482dfc51e0707f6554d81b0b4ec7bb6bbe62c9038775edd93a48004983c25b601d57aeb6b6e553a130ab154486451a1e3cdeef457cd79a4d1778b3055028399904d5c1a87374819fbc6c4407e1dcf7827a2fe06796116b563bee45f8ea8aded03d844b9ad5d9276f4b7b4c7623cd47ef941245e938518dc6631cbda26f514a682e97dc5a12631831d654d4a8b10ef061cf3f5f413308ad140dd43a7aa2058f04e9343df0c8738f74fbb1904cf87438e11c4ec3fb84e40e7b26be2a0016c2a1064a8cb26fe154770466f4a589068cb3270d8724798c87363719c42c298532
"""

"""
Simple U-Net model implementation in Keras for image segmentation tasks.
"""

from keras.models import Model
from keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D, concatenate, Conv2DTranspose, Dropout, Lambda
from keras.optimizers import Adam
from keras.metrics import MeanIoU

# Default kernel initializer
KERNEL_INITIALIZER = 'he_uniform'


def simple_unet_model(img_height, img_width, img_channels, num_classes=1, learning_rate=1e-3, normalize=False):
    """
    Builds a U-Net model for image segmentation.

    Args:
        img_height (int): Height of the input image.
        img_width (int): Width of the input image.
        img_channels (int): Number of channels in the input image (e.g., 3 for RGB).
        num_classes (int, optional): Number of output classes. Defaults to 1 (binary segmentation).
        learning_rate (float, optional): Learning rate for the optimizer. Defaults to 1e-3.
        normalize (bool, optional): Whether to normalize inputs to [0, 1]. Defaults to False.

    Returns:
        Model: Compiled Keras U-Net model.
    """
    inputs = Input((img_height, img_width, img_channels))

    # Optional input normalization
    if normalize:
        s = Lambda(lambda x: x / 255.0)(inputs)
    else:
        s = inputs

    # Contraction path
    c1 = Conv2D(16, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(s)
    c1 = Dropout(0.1)(c1)
    c1 = Conv2D(16, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(c1)
    p1 = MaxPooling2D((2, 2))(c1)

    c2 = Conv2D(32, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(p1)
    c2 = Dropout(0.1)(c2)
    c2 = Conv2D(32, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(c2)
    p2 = MaxPooling2D((2, 2))(c2)

    c3 = Conv2D(64, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(p2)
    c3 = Dropout(0.2)(c3)
    c3 = Conv2D(64, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(c3)
    p3 = MaxPooling2D((2, 2))(c3)

    c4 = Conv2D(128, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(p3)
    c4 = Dropout(0.2)(c4)
    c4 = Conv2D(128, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(c4)
    p4 = MaxPooling2D(pool_size=(2, 2))(c4)

    c5 = Conv2D(256, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(p4)
    c5 = Dropout(0.3)(c5)  # Higher dropout in bottleneck to prevent overfitting
    c5 = Conv2D(256, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(c5)

    # Expansive path
    u6 = Conv2DTranspose(128, (2, 2), strides=(2, 2), padding='same')(c5)
    u6 = concatenate([u6, c4])
    c6 = Conv2D(128, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(u6)
    c6 = Dropout(0.2)(c6)
    c6 = Conv2D(128, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(c6)

    u7 = Conv2DTranspose(64, (2, 2), strides=(2, 2), padding='same')(c6)
    u7 = concatenate([u7, c3])
    c7 = Conv2D(64, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(u7)
    c7 = Dropout(0.2)(c7)
    c7 = Conv2D(64, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(c7)

    u8 = Conv2DTranspose(32, (2, 2), strides=(2, 2), padding='same')(c7)
    u8 = concatenate([u8, c2])
    c8 = Conv2D(32, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(u8)
    c8 = Dropout(0.1)(c8)
    c8 = Conv2D(32, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(c8)

    u9 = Conv2DTranspose(16, (2, 2), strides=(2, 2), padding='same')(c8)
    u9 = concatenate([u9, c1], axis=3)
    c9 = Conv2D(16, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(u9)
    c9 = Dropout(0.1)(c9)
    c9 = Conv2D(16, (3, 3), activation='relu', kernel_initializer=KERNEL_INITIALIZER, padding='same')(c9)

    # Output layer: adjust activation based on number of classes
    if num_classes == 1:
        activation = 'sigmoid'
        loss = 'binary_crossentropy'
        metrics = ['accuracy']
    else:
        activation = 'softmax'
        loss = 'categorical_crossentropy'
        metrics = [MeanIoU(num_classes=num_classes)]

    outputs = Conv2D(num_classes, (1, 1), activation=activation)(c9)

    # Define and compile the model
    model = Model(inputs=[inputs], outputs=[outputs])
    model.compile(optimizer=Adam(learning_rate=learning_rate), loss=loss, metrics=metrics)
    model.summary()

    return model


if __name__ == "__main__":
    # Example usage
    model = simple_unet_model(img_height=256, img_width=256, img_channels=3, num_classes=1)