# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10C2a4yTv9SO6FW8i1fqCWZuWbV4Aiz92
"""

from unet import simple_unet_model
import numpy as np

# Dummy data
x_train = np.random.rand(10, 256, 256, 3)
y_train = np.random.randint(0, 2, (10, 256, 256, 1))

# Build and train model
model = simple_unet_model(256, 256, 3, num_classes=1)
model.fit(x_train, y_train, epochs=5, batch_size=2)